### ISSUE TITLE
Basic testing framework

### ISSUE THREAD

**Issue by thekrampus** [nealian/cse325_project2#11]
Really just some test cases. Cover interactive/batch input, semicolon-delimited commands, termination through `quit` and `EOF`, and memory leaks. Oh, and probably forking into bg with `&`, though it's not required.

**Comment by nealian** [comment]
I think I'm pulling the bg functionality; it's not entirely complicated with the concurrency, but it's at least a little complicated.

**Comment by thekrampus** [comment]
That works. It ain't required!
